/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Pavi
 */
public class AdminViewAppointment extends javax.swing.JFrame {
    String id;
    /**
     * Creates new form AdminViewAppointment
     */
    public AdminViewAppointment() {
        initComponents();
    }
    
    public AdminViewAppointment(String ID) {
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize,ysize);
        
        jAppointmentTable.getTableHeader().setFont(new Font("Raleway SemiBold", Font.PLAIN, 13));
        jAppointmentTable.getTableHeader().setForeground(Color.BLUE);
        id=ID;
        Connection con = null;
        PreparedStatement st=null;
        ResultSet rs = null;
        con = Link.getConnection();
        
        DefaultTableModel model=(DefaultTableModel)jAppointmentTable.getModel();
        model.setRowCount(0);
        String sql="select patient_id, doctor_id from patient_doctor where date=?";
        try{
        st=con.prepareStatement(sql);
        st.setString(1,java.time.LocalDate.now().toString());
        rs=st.executeQuery();
        while(rs.next()){
            String patient_id=rs.getString("patient_id");
            String doctor_id=rs.getString("doctor_id");
            
            PreparedStatement st1=null;
            ResultSet rs1 = null;
            String sql1="select * from patient where id=? ";
        
            PreparedStatement st2=null;
            ResultSet rs2 = null;
            String sql2="select * from doctor where id=? ";
            
            try{
            st1=con.prepareStatement(sql1);
            st1.setString(1,patient_id);
            rs1=st1.executeQuery();
            
            st2=con.prepareStatement(sql2);
            st2.setString(1,doctor_id);
            rs2=st2.executeQuery();
            
            
            int i=1;
            
            while(rs1.next() && rs2.next()){
                Object o[]={i,rs2.getString("name"),rs1.getString("name"),rs1.getString("phone"),rs1.getString("email")};
                model.addRow(o);
            }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jAppointmentTable = new javax.swing.JTable();
        jBack = new javax.swing.JLabel();
        jHome = new javax.swing.JLabel();
        jLogout = new javax.swing.JLabel();
        jClose = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSummary = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jAppointmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order", "Doctor Name", "Patient Name", "Patient Phone number", "Patient Email"
            }
        ));
        jScrollPane1.setViewportView(jAppointmentTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 880, 200));

        jBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back_1.png"))); // NOI18N
        jBack.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBackMouseMoved(evt);
            }
        });
        jBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackMouseClicked(evt);
            }
        });
        getContentPane().add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 580, -1, -1));

        jHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        jHome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jHomeMouseMoved(evt);
            }
        });
        jHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHomeMouseClicked(evt);
            }
        });
        getContentPane().add(jHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 60, -1, -1));

        jLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout_icon.png"))); // NOI18N
        jLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLogoutMouseMoved(evt);
            }
        });
        jLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(jLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 60, -1, -1));

        jClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jClose.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jCloseMouseMoved(evt);
            }
        });
        jClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 55, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/appointmenticon.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 150, 140));

        jLabel18.setFont(new java.awt.Font("Raleway Medium", 0, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Today Appointment");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 360, 50));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bar.png"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jSummary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/summary.png"))); // NOI18N
        jSummary.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jSummaryMouseMoved(evt);
            }
        });
        jSummary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSummaryMouseClicked(evt);
            }
        });
        getContentPane().add(jSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBackMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jBack.setCursor(cur1);
    }//GEN-LAST:event_jBackMouseMoved

    private void jBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackMouseClicked
        // TODO add your handling code here:
        AdminPanel panel =new AdminPanel(id);
        panel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBackMouseClicked

    private void jSummaryMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSummaryMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jSummary.setCursor(cur1);
    }//GEN-LAST:event_jSummaryMouseMoved

    private void jSummaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSummaryMouseClicked
        // TODO add your handling code here:
        int total=0;
        
        Connection con = null;
        PreparedStatement st=null;
        ResultSet rs = null;
        con = Link.getConnection();
        
        String sql="select count(*) as total from doctor";
        try{
        st=con.prepareStatement(sql);
        rs=st.executeQuery();
        while(rs.next()){
            total=rs.getInt("total");
        }
        }catch(Exception e){
           e.printStackTrace(); 
        }
        
        String[] doctor = new String[total];
        String[] doctor_id= new String[total];
        int[] income= new int[total];
        int count=0;
        
        PreparedStatement st1=null;
        ResultSet rs1 = null;
        String sql1="select distinct doctor_id from patient_doctor";
        try{
        st1=con.prepareStatement(sql1);
        rs1=st1.executeQuery();
        while(rs1.next()){
            doctor_id[count]=rs1.getString("doctor_id");
            
            PreparedStatement st2=null;
            ResultSet rs2 = null;
            String sql2="select * from doctor where id=? ";
            
            try{
            st2=con.prepareStatement(sql2);
            st2.setString(1,doctor_id[count]);
            rs2=st2.executeQuery();
            while(rs2.next()){
                doctor[count] = rs2.getString("name");
            }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            count++;
        }
        }catch(Exception e){
           e.printStackTrace(); 
        }
        
        int i=0;
        PreparedStatement st3=null;
        ResultSet rs3 = null;
        String sql3="select count(*) as income from patient_doctor group by doctor_id";
            
        try{
        st3=con.prepareStatement(sql3);
        rs3=st3.executeQuery();
        while(rs3.next()){
            income[i] = rs3.getInt("income");
            i++;
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
      
         DefaultCategoryDataset dataset= new DefaultCategoryDataset();
         for(int j=0;j<count;j++){
         dataset.setValue(income[j], "Number of Appoinmets", doctor[j]);
         }
         
         JFreeChart chart =ChartFactory.createBarChart("Summary of Doctors' appointments", "Doctor name", "Number of Appointments", dataset, PlotOrientation.VERTICAL, false, true, false);
         CategoryPlot p=chart.getCategoryPlot();
         p.setRangeGridlinePaint(Color.black);
         ChartFrame frame=new ChartFrame("Bar Chart for Summary of Doctors' appointments",chart);
         frame.setVisible(true);
         frame.setSize(600,500);
    }//GEN-LAST:event_jSummaryMouseClicked

    private void jHomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomeMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jHome.setCursor(cur1);
    }//GEN-LAST:event_jHomeMouseMoved

    private void jHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomeMouseClicked
        // TODO add your handling code here:
        AdminPanel panel = new AdminPanel(id);
        panel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jHomeMouseClicked

    private void jLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jLogout.setCursor(cur1);
    }//GEN-LAST:event_jLogoutMouseMoved

    private void jLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseClicked
        // TODO add your handling code here:
        LoginPanel panel = new LoginPanel();
        panel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLogoutMouseClicked

    private void jCloseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jClose.setCursor(cur1);
    }//GEN-LAST:event_jCloseMouseMoved

    private void jCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jAppointmentTable;
    private javax.swing.JLabel jBack;
    private javax.swing.JLabel jClose;
    private javax.swing.JLabel jHome;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLogout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jSummary;
    // End of variables declaration//GEN-END:variables
}
