/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.awt.Cursor;
import java.awt.Toolkit;

/**
 *
 * @author HP
 */
public class AdminPanel extends javax.swing.JFrame {
    String id;
    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    public AdminPanel(String ID){
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize,ysize);
        
        id=ID;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLogout = new javax.swing.JLabel();
        jClose = new javax.swing.JLabel();
        jProfile = new javax.swing.JLabel();
        jPatientDetails = new javax.swing.JLabel();
        jAppointments = new javax.swing.JLabel();
        jDoctor = new javax.swing.JLabel();
        jStaff = new javax.swing.JLabel();
        jChangePassword = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jWard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout_icon.png"))); // NOI18N
        jLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLogoutMouseMoved(evt);
            }
        });
        jLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(jLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 50, -1, -1));

        jClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jClose.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jCloseMouseMoved(evt);
            }
        });
        jClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 45, -1, -1));

        jProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile_front.png"))); // NOI18N
        jProfile.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jProfileMouseMoved(evt);
            }
        });
        jProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jProfileMouseClicked(evt);
            }
        });
        getContentPane().add(jProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, -1, -1));

        jPatientDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/patient_outside.png"))); // NOI18N
        jPatientDetails.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPatientDetailsMouseMoved(evt);
            }
        });
        jPatientDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPatientDetailsMouseClicked(evt);
            }
        });
        getContentPane().add(jPatientDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        jAppointments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/appointment_front.png"))); // NOI18N
        jAppointments.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jAppointmentsMouseMoved(evt);
            }
        });
        jAppointments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAppointmentsMouseClicked(evt);
            }
        });
        getContentPane().add(jAppointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));

        jDoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/doctors.png"))); // NOI18N
        jDoctor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jDoctorMouseMoved(evt);
            }
        });
        jDoctor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDoctorMouseClicked(evt);
            }
        });
        getContentPane().add(jDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 170, 200, 200));

        jStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/staffs.png"))); // NOI18N
        jStaff.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jStaffMouseMoved(evt);
            }
        });
        jStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jStaffMouseClicked(evt);
            }
        });
        getContentPane().add(jStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 170, -1, -1));

        jChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Reset Password.png"))); // NOI18N
        jChangePassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jChangePasswordMouseMoved(evt);
            }
        });
        jChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChangePasswordMouseClicked(evt);
            }
        });
        getContentPane().add(jChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 390, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adminicon2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 260, 190));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bar.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/welcome to admin portal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jWard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ward.png"))); // NOI18N
        jWard.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jWardMouseMoved(evt);
            }
        });
        jWard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jWardMouseClicked(evt);
            }
        });
        getContentPane().add(jWard, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jProfileMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProfileMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jProfile.setCursor(cur1);
    }//GEN-LAST:event_jProfileMouseMoved

    private void jPatientDetailsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPatientDetailsMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jPatientDetails.setCursor(cur1);
    }//GEN-LAST:event_jPatientDetailsMouseMoved

    private void jPatientDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPatientDetailsMouseClicked
        // TODO add your handling code here:
        AdminViewPatient profile=new AdminViewPatient(id);
        profile.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPatientDetailsMouseClicked

    private void jAppointmentsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAppointmentsMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jAppointments.setCursor(cur1);
    }//GEN-LAST:event_jAppointmentsMouseMoved

    private void jAppointmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAppointmentsMouseClicked
        // TODO add your handling code here:
        AdminViewAppointment view = new AdminViewAppointment(id);
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_jAppointmentsMouseClicked

    private void jDoctorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDoctorMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jDoctor.setCursor(cur1);
    }//GEN-LAST:event_jDoctorMouseMoved

    private void jDoctorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDoctorMouseClicked
        // TODO add your handling code here:
        ViewDoctor view=new ViewDoctor(id);
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_jDoctorMouseClicked

    private void jStaffMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStaffMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jStaff.setCursor(cur1);
    }//GEN-LAST:event_jStaffMouseMoved

    private void jStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStaffMouseClicked
        // TODO add your handling code here:
        ViewStaff view = new ViewStaff(id);
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_jStaffMouseClicked

    private void jProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProfileMouseClicked
        // TODO add your handling code here:
        AdminProfileView view = new AdminProfileView(id);
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_jProfileMouseClicked

    private void jChangePasswordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChangePasswordMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jChangePassword.setCursor(cur1);
    }//GEN-LAST:event_jChangePasswordMouseMoved

    private void jChangePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChangePasswordMouseClicked
        // TODO add your handling code here:
        AdminPasswordChange password = new AdminPasswordChange(id);
        password.setVisible(true);
        dispose();
    }//GEN-LAST:event_jChangePasswordMouseClicked

    private void jWardMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jWardMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jWard.setCursor(cur1);
    }//GEN-LAST:event_jWardMouseMoved

    private void jWardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jWardMouseClicked
        // TODO add your handling code here:
        AdminViewWard view = new AdminViewWard(id);
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_jWardMouseClicked

    private void jLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jLogout.setCursor(cur1);
    }//GEN-LAST:event_jLogoutMouseMoved

    private void jLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseClicked
        // TODO add your handling code here:
        LoginPanel login = new LoginPanel();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLogoutMouseClicked

    private void jCloseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jClose.setCursor(cur1);
    }//GEN-LAST:event_jCloseMouseMoved

    private void jCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAppointments;
    private javax.swing.JLabel jChangePassword;
    private javax.swing.JLabel jClose;
    private javax.swing.JLabel jDoctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLogout;
    private javax.swing.JLabel jPatientDetails;
    private javax.swing.JLabel jProfile;
    private javax.swing.JLabel jStaff;
    private javax.swing.JLabel jWard;
    // End of variables declaration//GEN-END:variables
}
