/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.awt.Cursor;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Pavi
 */
public class AdminAddWard extends javax.swing.JFrame {
    String id;
    String bed_no="-1";
    /**
     * Creates new form AdminAddWard
     */
    public AdminAddWard() {
        initComponents();
    }
    
    public AdminAddWard(String ID) {
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize,ysize);
        
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jBed.setVisible(false);
        jWard.setVisible(false);
        jAddWard.setVisible(false);
        
        id=ID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jAddWard = new javax.swing.JLabel();
        jBack = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jType = new javax.swing.JComboBox<>();
        jClose = new javax.swing.JLabel();
        jLogout = new javax.swing.JLabel();
        jHome = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jWard = new javax.swing.JTextField();
        jBed = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jViewProfile = new javax.swing.JMenu();
        jInsertProfile = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Quantity of Beds");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Ward Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, -1, -1));

        jAddWard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addNewWard.png"))); // NOI18N
        jAddWard.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jAddWardMouseMoved(evt);
            }
        });
        jAddWard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddWardMouseClicked(evt);
            }
        });
        getContentPane().add(jAddWard, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        jBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back_1.png"))); // NOI18N
        jBack.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBackMouseMoved(evt);
            }
        });
        jBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackMouseClicked(evt);
            }
        });
        getContentPane().add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));

        jLabel1.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Ward Type");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        jType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Luxury", "Normal" }));
        jType.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jTypePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(jType, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 200, 30));

        jClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jClose.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jCloseMouseMoved(evt);
            }
        });
        jClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 55, -1, -1));

        jLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout_icon.png"))); // NOI18N
        jLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLogoutMouseMoved(evt);
            }
        });
        jLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(jLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 60, -1, -1));

        jHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        jHome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jHomeMouseMoved(evt);
            }
        });
        jHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHomeMouseClicked(evt);
            }
        });
        getContentPane().add(jHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 60, -1, -1));

        jLabel18.setFont(new java.awt.Font("Raleway Medium", 0, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Add Ward");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 190, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addWard.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 140));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bar.png"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));
        getContentPane().add(jWard, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 200, 30));
        getContentPane().add(jBed, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 200, 30));

        jViewProfile.setText("View Ward");
        jViewProfile.setToolTipText("");
        jViewProfile.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jViewProfileMouseMoved(evt);
            }
        });
        jViewProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jViewProfileMouseClicked(evt);
            }
        });
        jMenuBar2.add(jViewProfile);

        jInsertProfile.setText("Insert Ward");
        jInsertProfile.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jInsertProfileMouseMoved(evt);
            }
        });
        jInsertProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInsertProfileMouseClicked(evt);
            }
        });
        jMenuBar2.add(jInsertProfile);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddWardMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddWardMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jAddWard.setCursor(cur1);
    }//GEN-LAST:event_jAddWardMouseMoved

    private void jAddWardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddWardMouseClicked
        // TODO add your handling code here:
        String ward_no=jWard.getText();
        String type=(String)jType.getSelectedItem();
        
        if(!bed_no.isEmpty() && !ward_no.isEmpty()){
        Connection con1 = null;
        PreparedStatement st1=null;
        ResultSet rs1 = null;
        con1 = Link.getConnection();
        String sql1 = "select * from ward where ward_no=?";
        try{
            st1=con1.prepareStatement(sql1);
            st1.setString(1,ward_no);
            rs1=st1.executeQuery();
            if(rs1.next()){
                JOptionPane.showMessageDialog(null,"Ward Number "+ward_no+" already added", 
                               "WARNING", JOptionPane.WARNING_MESSAGE);
            }else{
                if(!(bed_no.equals("0"))){
                bed_no=jBed.getText();
                }
                
                int foo = Integer.parseInt(bed_no);
                
                if (foo==0){
                    Connection con = null;
                PreparedStatement st=null;
                con = Link.getConnection();
                String sql="insert into ward(type, ward_no, bed_no, booked) values(?,?,?,?)";
                try{
                    st=con.prepareStatement(sql);
                    st.setString(1,type);
                    st.setString(2,ward_no);
                    st.setString(3,bed_no);
                    st.setString(4,"No");
                    st.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Insert Successfully");            
                    }
                catch(Exception e){
                    e.printStackTrace();
                    }
                }else{
                    for(int i=1;i<=foo;i++){
                        Connection con = null;
                PreparedStatement st=null;
                con = Link.getConnection();
                String sql="insert into ward(type, ward_no, bed_no, booked) values(?,?,?,?)";
                try{
                    st=con.prepareStatement(sql);
                    st.setString(1,type);
                    st.setString(2,ward_no);
                    st.setString(3,String.valueOf(i));
                    st.setString(4,"No");
                    st.executeUpdate();           
                    }
                catch(Exception e){
                    e.printStackTrace();
                    }
                    }
                    JOptionPane.showMessageDialog(null,"Insert Successfully"); 
                }      
                }
            }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
        }else if(bed_no.equals("0")){
            JOptionPane.showMessageDialog(null,"Please Enter Ward Number", 
                               "WARNING", JOptionPane.WARNING_MESSAGE);
        }else if(bed_no.equals("-1")){
            JOptionPane.showMessageDialog(null,"Please Enter Ward Number or Bed Number", 
                               "WARNING", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jAddWardMouseClicked

    private void jBackMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jBack.setCursor(cur1);
    }//GEN-LAST:event_jBackMouseMoved

    private void jBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackMouseClicked
        // TODO add your handling code here:
        AdminPanel panel=new AdminPanel(id);
        panel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBackMouseClicked

    private void jViewProfileMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jViewProfileMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jViewProfile.setCursor(cur1);
    }//GEN-LAST:event_jViewProfileMouseMoved

    private void jViewProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jViewProfileMouseClicked
        // TODO add your handling code here:
        AdminViewWard view=new AdminViewWard(id);
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_jViewProfileMouseClicked

    private void jInsertProfileMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInsertProfileMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jInsertProfile.setCursor(cur1);
    }//GEN-LAST:event_jInsertProfileMouseMoved

    private void jInsertProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInsertProfileMouseClicked
        // TODO add your handling code here:
        AdminAddWard insert=new AdminAddWard(id);
        insert.setVisible(true);
        dispose();
    }//GEN-LAST:event_jInsertProfileMouseClicked

    private void jTypePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jTypePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String type=(String)jType.getSelectedItem();
        if(type.equals("Normal")){
            jWard.setVisible(true);
            jBed.setVisible(true);
            jAddWard.setVisible(true);
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            bed_no="-1";
        }else if(type.equals("Luxury")){
            jWard.setVisible(true);
            jAddWard.setVisible(true);
            jLabel2.setVisible(true);
            jBed.setVisible(false);
            jLabel3.setVisible(false);
            bed_no="0";
        }else{
            jWard.setVisible(false);
            jBed.setVisible(false);
            jAddWard.setVisible(false);
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            bed_no="-1";
        }
    }//GEN-LAST:event_jTypePopupMenuWillBecomeInvisible

    private void jCloseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jClose.setCursor(cur1);
    }//GEN-LAST:event_jCloseMouseMoved

    private void jCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jCloseMouseClicked

    private void jLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jLogout.setCursor(cur1);
    }//GEN-LAST:event_jLogoutMouseMoved

    private void jLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseClicked
        // TODO add your handling code here:
        LoginPanel panel = new LoginPanel();
        panel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLogoutMouseClicked

    private void jHomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomeMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jHome.setCursor(cur1);
    }//GEN-LAST:event_jHomeMouseMoved

    private void jHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomeMouseClicked
        // TODO add your handling code here:
        AdminPanel panel = new AdminPanel(id);
        panel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddWard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddWard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddWard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddWard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddWard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAddWard;
    private javax.swing.JLabel jBack;
    private javax.swing.JTextField jBed;
    private javax.swing.JLabel jClose;
    private javax.swing.JLabel jHome;
    private javax.swing.JMenu jInsertProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLogout;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JComboBox<String> jType;
    private javax.swing.JMenu jViewProfile;
    private javax.swing.JTextField jWard;
    // End of variables declaration//GEN-END:variables
}
