/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.awt.Cursor;
import java.awt.Toolkit;

/**
 *
 * @author Pavi
 */
public class DoctorPanel extends javax.swing.JFrame {
    String id;
    /**
     * Creates new form DoctorPanel2
     */
    public DoctorPanel() {
        initComponents();
    }
    
    public DoctorPanel(String ID) {
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize,ysize);
        
        id=ID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jClose = new javax.swing.JLabel();
        jLogout = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPatientDetails = new javax.swing.JLabel();
        jProfile = new javax.swing.JLabel();
        jAppointment = new javax.swing.JLabel();
        jWardPatient = new javax.swing.JLabel();
        jChangePassword = new javax.swing.JLabel();
        jOPDPatient = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jClose.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jCloseMouseMoved(evt);
            }
        });
        jClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 45, -1, -1));

        jLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout_icon.png"))); // NOI18N
        jLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLogoutMouseMoved(evt);
            }
        });
        jLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(jLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 50, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bar.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/doctoricon.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/welcome to doctor portal.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jPatientDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/patient_outside.png"))); // NOI18N
        jPatientDetails.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPatientDetailsMouseMoved(evt);
            }
        });
        jPatientDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPatientDetailsMouseClicked(evt);
            }
        });
        getContentPane().add(jPatientDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        jProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile_front.png"))); // NOI18N
        jProfile.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jProfileMouseMoved(evt);
            }
        });
        jProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jProfileMouseClicked(evt);
            }
        });
        getContentPane().add(jProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, -1, -1));

        jAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/appointment_front.png"))); // NOI18N
        jAppointment.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jAppointmentMouseMoved(evt);
            }
        });
        jAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAppointmentMouseClicked(evt);
            }
        });
        getContentPane().add(jAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));

        jWardPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/patient_ward.png"))); // NOI18N
        jWardPatient.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jWardPatientMouseMoved(evt);
            }
        });
        jWardPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jWardPatientMouseClicked(evt);
            }
        });
        getContentPane().add(jWardPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, -1, -1));

        jChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Reset Password.png"))); // NOI18N
        jChangePassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jChangePasswordMouseMoved(evt);
            }
        });
        jChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChangePasswordMouseClicked(evt);
            }
        });
        getContentPane().add(jChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 390, -1, -1));

        jOPDPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/patient_OPD.png"))); // NOI18N
        jOPDPatient.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jOPDPatientMouseMoved(evt);
            }
        });
        jOPDPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOPDPatientMouseClicked(evt);
            }
        });
        getContentPane().add(jOPDPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPatientDetailsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPatientDetailsMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jPatientDetails.setCursor(cur1);
    }//GEN-LAST:event_jPatientDetailsMouseMoved

    private void jPatientDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPatientDetailsMouseClicked
        // TODO add your handling code here:
        ViewPatient view = new ViewPatient(id);
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPatientDetailsMouseClicked

    private void jProfileMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProfileMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jProfile.setCursor(cur1);
    }//GEN-LAST:event_jProfileMouseMoved

    private void jProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProfileMouseClicked
        // TODO add your handling code here:
        DoctorProfileView profile = new DoctorProfileView(id);
        profile.setVisible(true);
        dispose();
    }//GEN-LAST:event_jProfileMouseClicked

    private void jAppointmentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAppointmentMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jAppointment.setCursor(cur1);
    }//GEN-LAST:event_jAppointmentMouseMoved

    private void jAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAppointmentMouseClicked
        // TODO add your handling code here:
        CurrentPatient current = new CurrentPatient(id);
        current.setVisible(true);
        dispose();
    }//GEN-LAST:event_jAppointmentMouseClicked

    private void jWardPatientMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jWardPatientMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jWardPatient.setCursor(cur1);
    }//GEN-LAST:event_jWardPatientMouseMoved

    private void jWardPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jWardPatientMouseClicked
        // TODO add your handling code here:
        WardPatient patient = new WardPatient(id);
        patient.setVisible(true);
        dispose();
    }//GEN-LAST:event_jWardPatientMouseClicked

    private void jChangePasswordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChangePasswordMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jChangePassword.setCursor(cur1);
    }//GEN-LAST:event_jChangePasswordMouseMoved

    private void jChangePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChangePasswordMouseClicked
        // TODO add your handling code here:
        DoctorPasswordChange password = new DoctorPasswordChange(id);
        password.setVisible(true);
        dispose();
    }//GEN-LAST:event_jChangePasswordMouseClicked

    private void jOPDPatientMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOPDPatientMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jOPDPatient.setCursor(cur1);
    }//GEN-LAST:event_jOPDPatientMouseMoved

    private void jOPDPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOPDPatientMouseClicked
        // TODO add your handling code here:
        OPDPatient patient = new OPDPatient(id);
        patient.setVisible(true);
        dispose();
    }//GEN-LAST:event_jOPDPatientMouseClicked

    private void jLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jLogout.setCursor(cur1);
    }//GEN-LAST:event_jLogoutMouseMoved

    private void jLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseClicked
        // TODO add your handling code here:
        LoginPanel login = new LoginPanel();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLogoutMouseClicked

    private void jCloseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jClose.setCursor(cur1);
    }//GEN-LAST:event_jCloseMouseMoved

    private void jCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAppointment;
    private javax.swing.JLabel jChangePassword;
    private javax.swing.JLabel jClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLogout;
    private javax.swing.JLabel jOPDPatient;
    private javax.swing.JLabel jPatientDetails;
    private javax.swing.JLabel jProfile;
    private javax.swing.JLabel jWardPatient;
    // End of variables declaration//GEN-END:variables
}
