/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.awt.Cursor;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Objects;
import javax.swing.JOptionPane;

/**
 *
 * @author bosspavi
 */
public class LoginPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminLoginPanel
     */
    public LoginPanel() {
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize,ysize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jClose = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jUserName = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jLogin = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit_login.png"))); // NOI18N
        jClose.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jCloseMouseMoved(evt);
            }
        });
        jClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hospital.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LoginHere.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user2.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lock2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, -1, -1));
        getContentPane().add(jUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 220, 30));

        jPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 220, 30));

        jLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginbutton.png"))); // NOI18N
        jLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLoginMouseMoved(evt);
            }
        });
        jLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginMouseClicked(evt);
            }
        });
        getContentPane().add(jLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/white2.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginportal.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jLogin.setCursor(cur1);
    }//GEN-LAST:event_jLoginMouseMoved

    private void jLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginMouseClicked
        // TODO add your handling code here:
        Connection con=null;
        PreparedStatement st=null;
        ResultSet rs=null;
        con=Link.getConnection();
        String sql="select * from admin where username=? and password=?";
        try{
         st=con.prepareStatement(sql);
         st.setString(1,jUserName.getText());
         st.setString(2,jPassword.getText());
         rs=st.executeQuery();
         if(rs.next())
         {  
            String id=rs.getString("id");
            AdminPanel recept=new AdminPanel(id);
            recept.setVisible(true);
            dispose();
         }        
         else{
             String sql1="select * from doctor where username=? and password=?";
             try{
         st=con.prepareStatement(sql1);
         st.setString(1,jUserName.getText());
         st.setString(2,jPassword.getText());
         rs=st.executeQuery();
         if(rs.next())
         {  
            String id=rs.getString("id");
            DoctorPanel recept=new DoctorPanel(id);
            recept.setVisible(true);
            dispose();
         }
         
         else{
             String sql2="select * from staff where username=? and password=?";
             try{
         st=con.prepareStatement(sql2);
         st.setString(1,jUserName.getText());
         st.setString(2,jPassword.getText());
         rs=st.executeQuery();
         if(rs.next())
         {  
             String job=rs.getString("job");
            if(Objects.equals(job, "laboraty")){
             String id=rs.getString("id");
             LaboratyTechnicianPanel recept=new LaboratyTechnicianPanel(id);
            recept.setVisible(true);
            dispose();
            }
            
            else if(Objects.equals(job, "receptionist")){
             String id=rs.getString("id");
             ReceptionistPanel recept=new ReceptionistPanel(id);
            recept.setVisible(true);
            dispose();
            }
            
            else{
                String id=rs.getString("id");
             StaffPanel staff=new StaffPanel(id);
            staff.setVisible(true);
            dispose();
            }
            
         }
         else{
              JOptionPane.showMessageDialog(null,"Incorrect User Name or Password");
             jUserName.setText("");
             jPassword.setText("");
         }
             }
              
         catch(Exception e){
            e.printStackTrace();
            }
         }
         
             }
             catch(Exception e){
            e.printStackTrace();
        }
         }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLoginMouseClicked

    private void jPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            Connection con=null;
        PreparedStatement st=null;
        ResultSet rs=null;
        con=Link.getConnection();
        String sql="select * from admin where username=? and password=?";
        try{
         st=con.prepareStatement(sql);
         st.setString(1,jUserName.getText());
         st.setString(2,jPassword.getText());
         rs=st.executeQuery();
         if(rs.next())
         {  
            String id=rs.getString("id");
            AdminPanel recept=new AdminPanel(id);
            recept.setVisible(true);
            dispose();
         }        
         else{
             String sql1="select * from doctor where username=? and password=?";
             try{
         st=con.prepareStatement(sql1);
         st.setString(1,jUserName.getText());
         st.setString(2,jPassword.getText());
         rs=st.executeQuery();
         if(rs.next())
         {  
            String id=rs.getString("id");
            DoctorPanel recept=new DoctorPanel(id);
            recept.setVisible(true);
            dispose();
         }
         
         else{
             String sql2="select * from staff where username=? and password=?";
             try{
         st=con.prepareStatement(sql2);
         st.setString(1,jUserName.getText());
         st.setString(2,jPassword.getText());
         rs=st.executeQuery();
         if(rs.next())
         {  
             String job=rs.getString("job");
            if(Objects.equals(job, "laboraty")){
             String id=rs.getString("id");
             LaboratyTechnicianPanel recept=new LaboratyTechnicianPanel(id);
            recept.setVisible(true);
            dispose();
            }
            
            else if(Objects.equals(job, "receptionist")){
             String id=rs.getString("id");
             ReceptionistPanel recept=new ReceptionistPanel(id);
            recept.setVisible(true);
            dispose();
            }
            
         }
         else{
              JOptionPane.showMessageDialog(null,"Incorrect User Name or Password");
             jUserName.setText("");
             jPassword.setText("");
         }
             }
              
         catch(Exception e){
            e.printStackTrace();
            }
         }
         
             }
             catch(Exception e){
            e.printStackTrace();
        }
         }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jPasswordKeyPressed

    private void jCloseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jClose.setCursor(cur1);
    }//GEN-LAST:event_jCloseMouseMoved

    private void jCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLogin;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jUserName;
    // End of variables declaration//GEN-END:variables
}
