/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.awt.Cursor;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.Month;
import java.time.YearMonth;
import java.time.temporal.TemporalAdjusters;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.EnumSet;
import java.util.Set;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class MakeAppointment extends javax.swing.JFrame {
    String id;
    String value;
    String clinic;
    String doc_id;
    String day;
    String date;
    ArrayList<LocalDate> dates;
    String first;
    /**
     * Creates new form AddSearchAppointment
     */
    public MakeAppointment() {
        initComponents(); 
    }
    
    public MakeAppointment(String ID) {
        initComponents();  
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize,ysize);
        
        jLabel14.setVisible(false);
        jDoctor.setVisible(false);
        jAppointment.setVisible(false);
        jClinic.setVisible(false);
        jLabel8.setVisible(false);
        jLabel1.setVisible(false);
        jDay.setVisible(false);
        jLabel7.setVisible(false);
        jDate.setVisible(false);
        
        first = jFirst.getText();
        
        id=ID;
    }
    
    public MakeAppointment(String ID,String Value) {
        initComponents();  
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize,ysize);
        
        jLabel14.setVisible(false);
        jDoctor.setVisible(false);
        jAppointment.setVisible(false);
        jClinic.setVisible(false);
        jLabel8.setVisible(false);
        jLabel1.setVisible(false);
        jDay.setVisible(false);
        jLabel7.setVisible(false);
        jDate.setVisible(false);
        
        id=ID;
        value=Value;
        
        Connection con = null;
        PreparedStatement st=null;
        ResultSet rs = null;
        con = Link.getConnection();
        String sql="select * from patient where id=?";
        try{
            st=con.prepareStatement(sql);
            st.setString(1,value);
            rs=st.executeQuery();

            if(rs.next()){
                jFirst.setText(rs.getString("name"));
                jLast.setText(rs.getString("surname"));
                jAge.setText(rs.getString("age"));
                jGender.setText(rs.getString("gender"));
                jBlood.setText(rs.getString("blood"));
                jAddress.setText(rs.getString("address"));
                jCity.setText(rs.getString("city"));
                jEmail.setText(rs.getString("email"));
                jPhone.setText(rs.getString("phone"));
                jNIC.setText(rs.getString("NIC"));
                
                jClinic.setVisible(true);
                jLabel8.setVisible(true);
                
                first = jFirst.getText();
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
    public JFrame getClosed(){
        MakeAppointment close=this;
        return close;
    }
    
    public JLabel getReturn(){
        return jSearch; 
    }
    
    public JLabel getBack(){
        return jBack; 
    }
    
    public JLabel getWell(){
        return jLabel8;
    }
    
    public JComboBox getVisible(){
        return jClinic; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSearch = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jAppointment = new javax.swing.JLabel();
        jBack = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jClinic = new javax.swing.JComboBox<>();
        jDoctor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jDay = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jDate = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jFirst = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jAge = new javax.swing.JTextField();
        jBlood = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jAddress = new javax.swing.JTextField();
        jCity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPhone = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jNIC = new javax.swing.JTextField();
        jDate1 = new javax.swing.JTextField();
        jEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLast = new javax.swing.JTextField();
        jGender = new javax.swing.JTextField();
        jHome = new javax.swing.JLabel();
        jLogout = new javax.swing.JLabel();
        jClose = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search patient.png"))); // NOI18N
        jSearch.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jSearchMouseMoved(evt);
            }
        });
        jSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSearchMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSearchMousePressed(evt);
            }
        });
        getContentPane().add(jSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(11, 159, 207));
        jLabel14.setText("Doctor full name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, -1, -1));

        jAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bookAppointment.png"))); // NOI18N
        jAppointment.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jAppointmentMouseMoved(evt);
            }
        });
        jAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAppointmentMouseClicked(evt);
            }
        });
        getContentPane().add(jAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, -1, -1));

        jBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back_1.png"))); // NOI18N
        jBack.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBackMouseMoved(evt);
            }
        });
        jBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackMouseClicked(evt);
            }
        });
        getContentPane().add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 580, -1, -1));

        jLabel8.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(11, 159, 207));
        jLabel8.setText("Clinic Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, -1, -1));

        jClinic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jClinic.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jClinicMouseMoved(evt);
            }
        });
        jClinic.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jClinicPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(jClinic, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 140, 30));

        jDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jDoctor.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jDoctorPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(jDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 200, 30));

        jLabel1.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(11, 159, 207));
        jLabel1.setText("Day");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, -1, -1));

        jDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jDay.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jDayPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(jDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 140, 30));

        jLabel7.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(11, 159, 207));
        jLabel7.setText("Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, -1, -1));

        jDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jDate.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jDatePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(jDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 140, 30));

        jLabel2.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(11, 159, 207));
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jFirst.setEditable(false);
        getContentPane().add(jFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 140, 30));

        jLabel4.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(11, 159, 207));
        jLabel4.setText("Age");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jAge.setEditable(false);
        getContentPane().add(jAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 140, 30));

        jBlood.setEditable(false);
        getContentPane().add(jBlood, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 140, 30));

        jLabel6.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(11, 159, 207));
        jLabel6.setText("Blood type");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(11, 159, 207));
        jLabel9.setText("Address");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jAddress.setEditable(false);
        getContentPane().add(jAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 280, 30));

        jCity.setEditable(false);
        getContentPane().add(jCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 140, 30));

        jLabel10.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(11, 159, 207));
        jLabel10.setText("City");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel11.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(11, 159, 207));
        jLabel11.setText("Phone No.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jPhone.setEditable(false);
        getContentPane().add(jPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 140, 30));

        jLabel16.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(11, 159, 207));
        jLabel16.setText("Date");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        jLabel12.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(11, 159, 207));
        jLabel12.setText("NIC");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        jNIC.setEditable(false);
        getContentPane().add(jNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 140, 30));

        jDate1.setEditable(false);
        getContentPane().add(jDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 140, 30));

        jEmail.setEditable(false);
        getContentPane().add(jEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 190, 30));

        jLabel13.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(11, 159, 207));
        jLabel13.setText("Email");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(11, 159, 207));
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        jLabel31.setFont(new java.awt.Font("Raleway SemiBold", 0, 13)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(11, 159, 207));
        jLabel31.setText("Last Name");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jLast.setEditable(false);
        getContentPane().add(jLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 140, 30));

        jGender.setEditable(false);
        getContentPane().add(jGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 140, 30));

        jHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        jHome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jHomeMouseMoved(evt);
            }
        });
        jHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHomeMouseClicked(evt);
            }
        });
        getContentPane().add(jHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 60, -1, -1));

        jLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout_icon.png"))); // NOI18N
        jLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLogoutMouseMoved(evt);
            }
        });
        jLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(jLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 60, -1, -1));

        jClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jClose.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jCloseMouseMoved(evt);
            }
        });
        jClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 55, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/appointmenticon.png"))); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 150, 140));

        jLabel28.setFont(new java.awt.Font("Raleway Medium", 0, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Booking Appointment");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 370, 50));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bar.png"))); // NOI18N
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSearchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jSearch.setCursor(cur1);
    }//GEN-LAST:event_jSearchMouseMoved

    private void jSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchMouseClicked
        // TODO add your handling code here:
        jBack.setVisible(false);
        jSearch.setVisible(false);
        JFrame frame=this.getClosed();
        JLabel label=this.getReturn();
        JLabel label2=this.getBack();
        JLabel label3=this.getWell();
        JComboBox combo=this.getVisible();
        MakeAppointmentList list = new MakeAppointmentList(id,frame,label,label2,label3,combo,first);
        list.setVisible(true);
    }//GEN-LAST:event_jSearchMouseClicked

    private void jAppointmentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAppointmentMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jAppointment.setCursor(cur1);
    }//GEN-LAST:event_jAppointmentMouseMoved

    private void jAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAppointmentMouseClicked
        // TODO add your handling code here:
        Connection con = null;
        PreparedStatement st=null;
        con = Link.getConnection();
        String sql=("insert into patient_doctor(patient_id,doctor_id,date,done) values(?,?,?,?)");
        try{
            st=con.prepareStatement(sql);
            st.setString(1,value);
            st.setString(2,doc_id);
            st.setString(3,date);
            st.setString(4,"No");
            st.execute();

            JOptionPane.showMessageDialog(null,"Appointed");
            
            jFirst.setText("");
            jLast.setText("");
            jAge.setText("");
            jGender.setText("");
            jBlood.setText("");
            jAddress.setText("");
            jEmail.setText("");
            jPhone.setText("");
            jCity.setText("");
            jNIC.setText("");
            
            jLabel14.setVisible(false);
        jDoctor.setVisible(false);
        jAppointment.setVisible(false);
        jClinic.setVisible(false);
        jLabel8.setVisible(false);
        jLabel1.setVisible(false);
        jDay.setVisible(false);
        jLabel7.setVisible(false);
        jDate.setVisible(false);
        
        
        jClinic.removeAllItems();
        jClinic.addItem("Select");
        jDoctor.removeAllItems();
        jDoctor.addItem("Select");
        jDay.removeAllItems();
        jDay.addItem("Select");
        jDate.removeAllItems();
        jDate.addItem("Select");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Please enter the doctor", 
                               "WARNING", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jAppointmentMouseClicked

    private void jBackMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jBack.setCursor(cur1);
    }//GEN-LAST:event_jBackMouseMoved

    private void jBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackMouseClicked
        // TODO add your handling code here:
        ReceptionistPanel portal=new ReceptionistPanel(id);
        portal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBackMouseClicked

    private void jClinicMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClinicMouseMoved
        // TODO add your handling code here:
        int items = jClinic.getItemCount();
        
        if(items==1){
            Connection con = null;
            PreparedStatement st=null;
            ResultSet rs = null;
            con = Link.getConnection();
            String sql="select distinct specialization from doctor where id in (select doctor_id from time_table)";
            try{
            st=con.prepareStatement(sql);
            rs=st.executeQuery();
            while(rs.next()){
                jClinic.addItem(rs.getString("specialization"));
            }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
        
    }//GEN-LAST:event_jClinicMouseMoved

    private void jClinicPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jClinicPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        jLabel14.setVisible(false);
        jDoctor.setVisible(false);
        jLabel1.setVisible(false);
        jDay.setVisible(false);
        jLabel7.setVisible(false);
        jDate.setVisible(false);
        jAppointment.setVisible(false);
        
        jDoctor.removeAllItems();
        jDoctor.addItem("Select");
        jDay.removeAllItems();
        jDay.addItem("Select");
        jDate.removeAllItems();
        jDate.addItem("Select");
        
        clinic=(String)jClinic.getSelectedItem();
        if(!clinic.equals("Select")){
            jLabel14.setVisible(true);
            jDoctor.setVisible(true);
            
            jDoctor.removeAllItems();
            jDoctor.addItem("Select");
            Connection con = null;
            PreparedStatement st=null;
            ResultSet rs = null;
            con = Link.getConnection();
            String sql="select full_name from doctor where specialization=? and id in (select doctor_id from time_table)";
            try{
            st=con.prepareStatement(sql);
            st.setString(1,clinic);
            rs=st.executeQuery();
            while(rs.next()){
                jDoctor.addItem(rs.getString("full_name"));
            }
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            }
        } 
    }//GEN-LAST:event_jClinicPopupMenuWillBecomeInvisible

    private void jDoctorPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jDoctorPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        jLabel1.setVisible(false);
        jDay.setVisible(false);
        jLabel7.setVisible(false);
        jDate.setVisible(false);
        jAppointment.setVisible(false);
        
        jDay.removeAllItems();
        jDay.addItem("Select");
        jDate.removeAllItems();
        jDate.addItem("Select");
        
        String doctor=(String)jDoctor.getSelectedItem();
        if(!doctor.equals("Select")){
           Connection con = null;
        PreparedStatement st=null;
        ResultSet rs = null;
        con = Link.getConnection();
        String sql="select id from doctor where full_name=?";
        try{
        st=con.prepareStatement(sql);
        st.setString(1,doctor);
        rs=st.executeQuery();
        if(rs.next()){
            doc_id=rs.getString("id");
        } 
            jLabel1.setVisible(true);
            jDay.setVisible(true);
            
            jDay.removeAllItems();
            jDay.addItem("Select");
            con = Link.getConnection();
            String sql1="select distinct day from time_table where doctor_id=?";
            try{
            st=con.prepareStatement(sql1);
            st.setString(1,doc_id);
            rs=st.executeQuery();
            while(rs.next()){
            jDay.addItem(rs.getString("day"));
            }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
               
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        } 
        }        
    }//GEN-LAST:event_jDoctorPopupMenuWillBecomeInvisible

    private void jSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSearchMousePressed
        // TODO add your handling code here:
        jLabel14.setVisible(false);
        jDoctor.setVisible(false);
        jAppointment.setVisible(false);
        jClinic.setVisible(false);
        jLabel8.setVisible(false);
        jLabel1.setVisible(false);
        jDay.setVisible(false);
        jLabel7.setVisible(false);
        jDate.setVisible(false);
    }//GEN-LAST:event_jSearchMousePressed

    private void jDayPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jDayPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        jLabel7.setVisible(false);
        jDate.setVisible(false);
        jAppointment.setVisible(false);
        
        jDate.removeAllItems();
        jDate.addItem("Select");
        
        day=(String)jDay.getSelectedItem();
        if(!day.equals("Select")){
            jLabel7.setVisible(true);
            jDate.setVisible(true); 
            
            jDate.removeAllItems();
        jDate.addItem("Select");
        
        Calendar c = Calendar.getInstance();
                        int year = c.get(Calendar.YEAR);
                        int month = c.get(Calendar.MONTH);
                        int week = c.get(Calendar.WEEK_OF_MONTH);

                        String[] monthName = {"January", "February",
                                "March", "April", "May", "June", "July",
                                "August", "September", "October", "November",
                                "December"};

                        String name_of_month = monthName[month];

                        Set<DayOfWeek> daysOfWeek = EnumSet.noneOf ( DayOfWeek.class );
                        daysOfWeek.add ( DayOfWeek.valueOf(day.toUpperCase()) );

                        YearMonth ym = YearMonth.of ( year , Month.valueOf(name_of_month.toUpperCase()) );  // Or ( 2017 , 1 ) for January.

                        LocalDate firstOfMonth = ym.atDay ( 1 );

                        for ( DayOfWeek dayOfWeek : daysOfWeek ) {
                            dates = new ArrayList<> ( 5 );
                            LocalDate ld = firstOfMonth.with ( TemporalAdjusters.dayOfWeekInMonth ( week , dayOfWeek ) );
                            do {
                                if(ld.compareTo(java.time.LocalDate.now())>=0){
                                    dates.add ( ld );
                                    jDate.addItem(ld.toString());
                                }
                                // Set up next loop.
                                ld = ld.plusWeeks ( 1 );
                            } while ( YearMonth.from ( ld ).equals ( ym ) );  // While in the targeted month.
                        }
                        
                        if(dates.size()<5){
                        String name_of_next_month = monthName[month+1];

                        Set<DayOfWeek> daysOfWeek2 = EnumSet.noneOf ( DayOfWeek.class );
                        daysOfWeek2.add ( DayOfWeek.valueOf(day.toUpperCase()) );

                        YearMonth ym2 = YearMonth.of ( year , Month.valueOf(name_of_next_month.toUpperCase()) );  // Or ( 2017 , 1 ) for January.

                        LocalDate firstOfMonth2 = ym2.atDay ( 1 );

                        for ( DayOfWeek dayOfWeek : daysOfWeek ) {
                            LocalDate ld2 = firstOfMonth2.with ( TemporalAdjusters.dayOfWeekInMonth ( week , dayOfWeek ) );
                            do {
                                
                                    dates.add ( ld2 );
                                    jDate.addItem(ld2.toString());

                                if(dates.size()==5){
                                    break;
                                }
                                // Set up next loop.
                                ld2 = ld2.plusWeeks ( 1 );
                            } while ( YearMonth.from ( ld2).equals ( ym2 ) );  // While in the targeted month.
                        }
                        }
            
        }        
    }//GEN-LAST:event_jDayPopupMenuWillBecomeInvisible

    private void jDatePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jDatePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        date=(String)jDate.getSelectedItem();
        if(!date.equals("Select")){
            jAppointment.setVisible(true);
        }    
    }//GEN-LAST:event_jDatePopupMenuWillBecomeInvisible

    private void jHomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomeMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jHome.setCursor(cur1);
    }//GEN-LAST:event_jHomeMouseMoved

    private void jHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jHomeMouseClicked
        // TODO add your handling code here:
        ReceptionistPanel panel = new ReceptionistPanel(id);
        panel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jHomeMouseClicked

    private void jLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jLogout.setCursor(cur1);
    }//GEN-LAST:event_jLogoutMouseMoved

    private void jLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseClicked
        // TODO add your handling code here:
        LoginPanel panel = new LoginPanel();
        panel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLogoutMouseClicked

    private void jCloseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jClose.setCursor(cur1);
    }//GEN-LAST:event_jCloseMouseMoved

    private void jCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAddress;
    private javax.swing.JTextField jAge;
    private javax.swing.JLabel jAppointment;
    private javax.swing.JLabel jBack;
    private javax.swing.JTextField jBlood;
    private javax.swing.JTextField jCity;
    private javax.swing.JComboBox<String> jClinic;
    private javax.swing.JLabel jClose;
    private javax.swing.JComboBox<String> jDate;
    private javax.swing.JTextField jDate1;
    private javax.swing.JComboBox<String> jDay;
    private javax.swing.JComboBox<String> jDoctor;
    private javax.swing.JTextField jEmail;
    private javax.swing.JTextField jFirst;
    private javax.swing.JTextField jGender;
    private javax.swing.JLabel jHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLast;
    private javax.swing.JLabel jLogout;
    private javax.swing.JTextField jNIC;
    private javax.swing.JTextField jPhone;
    private javax.swing.JLabel jSearch;
    // End of variables declaration//GEN-END:variables
}
