/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.management.system;

import java.awt.Cursor;
import java.awt.Toolkit;

/**
 *
 * @author bosspavi
 */
public class ReceptionistPanel extends javax.swing.JFrame {
    String id;
    /**
     * Creates new form ReceptionistPortal
     */
    public ReceptionistPanel() {
        initComponents();
    }
    
    public ReceptionistPanel(String ID){
        initComponents();
        Toolkit tk=Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize,ysize);
        
        id=ID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLogout = new javax.swing.JLabel();
        jClose = new javax.swing.JLabel();
        jProfile = new javax.swing.JLabel();
        jAppointments = new javax.swing.JLabel();
        jNewPatient = new javax.swing.JLabel();
        jWardBooking = new javax.swing.JLabel();
        jOperationBooking = new javax.swing.JLabel();
        jTestBooking = new javax.swing.JLabel();
        jChangePassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout_icon.png"))); // NOI18N
        jLogout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLogoutMouseMoved(evt);
            }
        });
        jLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLogoutMouseClicked(evt);
            }
        });
        getContentPane().add(jLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 50, -1, -1));

        jClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jClose.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jCloseMouseMoved(evt);
            }
        });
        jClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCloseMouseClicked(evt);
            }
        });
        getContentPane().add(jClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 45, -1, -1));

        jProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile_front.png"))); // NOI18N
        jProfile.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jProfileMouseMoved(evt);
            }
        });
        jProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jProfileMouseClicked(evt);
            }
        });
        getContentPane().add(jProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, -1, -1));

        jAppointments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bookingAppointment.png"))); // NOI18N
        jAppointments.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jAppointmentsMouseMoved(evt);
            }
        });
        jAppointments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAppointmentsMouseClicked(evt);
            }
        });
        getContentPane().add(jAppointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));

        jNewPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/patient_outside.png"))); // NOI18N
        jNewPatient.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jNewPatientMouseMoved(evt);
            }
        });
        jNewPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNewPatientMouseClicked(evt);
            }
        });
        getContentPane().add(jNewPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        jWardBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/booking ward.png"))); // NOI18N
        jWardBooking.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jWardBookingMouseMoved(evt);
            }
        });
        jWardBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jWardBookingMouseClicked(evt);
            }
        });
        getContentPane().add(jWardBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 170, -1, -1));

        jOperationBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/booking operation.png"))); // NOI18N
        jOperationBooking.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jOperationBookingMouseMoved(evt);
            }
        });
        jOperationBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOperationBookingMouseClicked(evt);
            }
        });
        getContentPane().add(jOperationBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, -1, -1));

        jTestBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/booking tests.png"))); // NOI18N
        jTestBooking.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jTestBookingMouseMoved(evt);
            }
        });
        jTestBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTestBookingMouseClicked(evt);
            }
        });
        getContentPane().add(jTestBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 170, -1, -1));

        jChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Reset Password.png"))); // NOI18N
        jChangePassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jChangePasswordMouseMoved(evt);
            }
        });
        jChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChangePasswordMouseClicked(evt);
            }
        });
        getContentPane().add(jChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receptionisticon2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bar.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/welcome to receptionist portal.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAppointmentsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAppointmentsMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jAppointments.setCursor(cur1);
    }//GEN-LAST:event_jAppointmentsMouseMoved

    private void jAppointmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAppointmentsMouseClicked
        // TODO add your handling code here:
        MakeAppointment add=new MakeAppointment(id);
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_jAppointmentsMouseClicked

    private void jProfileMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProfileMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jProfile.setCursor(cur1);
    }//GEN-LAST:event_jProfileMouseMoved

    private void jProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProfileMouseClicked
        // TODO add your handling code here:
        StaffProfileView profile=new StaffProfileView(id);
        profile.setVisible(true);
        dispose();
    }//GEN-LAST:event_jProfileMouseClicked

    private void jNewPatientMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNewPatientMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jNewPatient.setCursor(cur1);
    }//GEN-LAST:event_jNewPatientMouseMoved

    private void jNewPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNewPatientMouseClicked
        // TODO add your handling code here:
        AddNewPatient patient=new AddNewPatient(id);
        patient.setVisible(true);
        dispose();
    }//GEN-LAST:event_jNewPatientMouseClicked

    private void jWardBookingMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jWardBookingMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jWardBooking.setCursor(cur1);
    }//GEN-LAST:event_jWardBookingMouseMoved

    private void jWardBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jWardBookingMouseClicked
        // TODO add your handling code here:
        WardBooking booking=new WardBooking(id);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_jWardBookingMouseClicked

    private void jOperationBookingMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOperationBookingMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jOperationBooking.setCursor(cur1);
    }//GEN-LAST:event_jOperationBookingMouseMoved

    private void jOperationBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOperationBookingMouseClicked
        // TODO add your handling code here:
        OperationBooking booking=new OperationBooking(id);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_jOperationBookingMouseClicked

    private void jTestBookingMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTestBookingMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jTestBooking.setCursor(cur1);
    }//GEN-LAST:event_jTestBookingMouseMoved

    private void jTestBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTestBookingMouseClicked
        // TODO add your handling code here:
        TestBooking booking=new TestBooking(id);
        booking.setVisible(true);
        dispose();
    }//GEN-LAST:event_jTestBookingMouseClicked

    private void jChangePasswordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChangePasswordMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jChangePassword.setCursor(cur1);
    }//GEN-LAST:event_jChangePasswordMouseMoved

    private void jChangePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChangePasswordMouseClicked
        // TODO add your handling code here:
        StaffPasswordChange password = new StaffPasswordChange(id);
        password.setVisible(true);
        dispose();
    }//GEN-LAST:event_jChangePasswordMouseClicked

    private void jLogoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jLogout.setCursor(cur1);
    }//GEN-LAST:event_jLogoutMouseMoved

    private void jLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLogoutMouseClicked
        // TODO add your handling code here:
        LoginPanel login = new LoginPanel();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLogoutMouseClicked

    private void jCloseMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseMoved
        // TODO add your handling code here:
        Cursor cur1=new Cursor(Cursor.HAND_CURSOR);
        jClose.setCursor(cur1);
    }//GEN-LAST:event_jCloseMouseMoved

    private void jCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionistPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAppointments;
    private javax.swing.JLabel jChangePassword;
    private javax.swing.JLabel jClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLogout;
    private javax.swing.JLabel jNewPatient;
    private javax.swing.JLabel jOperationBooking;
    private javax.swing.JLabel jProfile;
    private javax.swing.JLabel jTestBooking;
    private javax.swing.JLabel jWardBooking;
    // End of variables declaration//GEN-END:variables
}
